### ISSUE TITLE
Main push, layout and main

### ISSUE THREAD

**Issue by mihaiJianu** [Torkin1/biometric_prompt_WALL-E#7]
added **layout** of 
activity_main.xml

**drawable** 
gradient_1.xml
gradient_2.xml
gradient_3.xml
gradient_list.xml
+ various media

**values**
colors.xml
strings.xml
stles.xml

**Gradle**
build.gradle

**manifest**
AndroidManifest.xml

**Comment by Torkin1** [comment]
Deleted commented code and written some todos and added missing files
